# Generates js/data/*.js from the XML literals embedded in the decompiled
# ActionScript (CustomizationOptions, MoodOptions, PokeOptions).
import re, json
import xml.etree.ElementTree as ET
base = '../scripts/buddypoke/render/'

def xml_literal(path, start_tag):
    src = open(base + path).read()
    i = src.index('<' + start_tag)
    j = src.index('</' + start_tag + '>', i) + len(start_tag) + 3
    return ET.fromstring(src[i:j])

opts = xml_literal('CustomizationOptions.as', 'options')
options = []
for op in opts.findall('option'):
    items = []
    for sub in op:
        d = {'type': sub.tag, 'path': sub.get('path'), 'id': sub.get('id')}
        copies = [c.get('path') for c in sub.findall('copy')]
        if copies: d['copies'] = copies
        items.append(d)
    options.append({'name': op.get('name'), 'items': items})

# The customisable background (catalog materialOption "Bkg"), which the
# canvas app exposed next to the appearance options.
options.append({'name': 'Background', 'items': [
    {'type': 'color', 'path': 'Bkg;Material;Solid;Bkg_Solid', 'id': 'bg0'},
    {'type': 'texture', 'path': 'Bkg;Material;Pattern1', 'id': 'bg1'},
    {'type': 'color', 'path': 'Bkg;Material;Pattern1Color;BlankClip', 'id': 'bg1c'}]})
options.append({'name': 'Background 2', 'items': [
    {'type': 'texture', 'path': 'Bkg;Material;Pattern2', 'id': 'bg2'},
    {'type': 'color', 'path': 'Bkg;Material;Pattern2Color;BlankClip', 'id': 'bg2c'}]})
options.append({'name': 'Background 3', 'items': [
    {'type': 'texture', 'path': 'Bkg;Material;Pattern3', 'id': 'bg3'},
    {'type': 'color', 'path': 'Bkg;Material;Pattern3Color;BlankClip', 'id': 'bg3c'},
    {'type': 'texture', 'path': 'Bkg;Material;Pattern4', 'id': 'bg4'}]})

moods = xml_literal('MoodOptions.as', 'moods')
pokes = xml_literal('PokeOptions.as', 'anims')
def conv(el, tag):
    return {'defaults': dict(el.attrib), 'list': [dict(m.attrib) for m in el.findall(tag)]}

with open('js/data/options.js', 'w') as f:
    f.write('// Generated by tools/build_data.py from CustomizationOptions.as\n')
    f.write('export const CUSTOMIZATION_OPTIONS = ' + json.dumps(options, indent=1) + ';\n')
with open('js/data/moods.js', 'w') as f:
    f.write('// Generated by tools/build_data.py from MoodOptions.as and PokeOptions.as\n')
    f.write('export const MOODS = ' + json.dumps(conv(moods, 'mood'), indent=1) + ';\n')
    f.write('export const POKES = ' + json.dumps(conv(pokes, 'anim'), indent=1) + ';\n')
print(len(options), 'options;', len(moods.findall('mood')), 'moods;', len(pokes.findall('anim')), 'pokes')
